# -*- coding: utf-8 -*-
"""front.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsPYsagkVwzcvijraH80V05WmJTQmg1s
"""

!pip install streamlit
import streamlit as st
import pickle
import pandas as pd

st.set_page_config(page_title="Salary Prediction App", layout="centered")

# --- Load the pre-trained model ---
try:
    # Assuming the model is saved as 'linear_regression_model.pkl'
    with open('linear_regression_model.pkl', 'rb') as file:
        model = pickle.load(file)
    st.success("Model loaded successfully!")
except FileNotFoundError:
    st.error("Error: 'linear_regression_model.pkl' not found. Please ensure the model file is in the correct directory.")
    st.stop() # Stop the app if the model can't be loaded
except Exception as e:
    st.error(f"An error occurred while loading the model: {e}")
    st.stop()

# --- Streamlit App Interface ---
st.title("Salary Prediction with Linear Regression")
st.write("Enter the years of experience to predict the corresponding salary.")

# Input widget for years of experience
years_experience = st.slider(
    "Years of Experience",
    min_value=0.0,
    max_value=20.0,
    value=5.0,
    step=0.5,
    help="Drag the slider to select the years of experience"
)

# Make prediction
if st.button("Predict Salary"):
    try:
        # Create a DataFrame for the prediction input
        input_df = pd.DataFrame({'YearsExperience': [years_experience]})

        # Predict salary
        predicted_salary = model.predict(input_df)[0]

        st.subheader("Prediction")
        st.success(f"Predicted Salary: ${predicted_salary:,.2f}")
    except Exception as e:
        st.error(f"An error occurred during prediction: {e}")

st.markdown("---")
st.write("This app uses a simple linear regression model to predict salary.")

# Instructions to run the app
st.sidebar.header("How to run this app?")
st.sidebar.info("""1. Save this code as `app.py`.
2. Open your terminal or command prompt.
3. Navigate to the directory where you saved `app.py`.
4. Run the command: `streamlit run app.py`""")

# Commented out IPython magic to ensure Python compatibility.
# # Install localtunnel
# !npm install -g localtunnel
# 
# # Save the Streamlit app code to app.py
# %%writefile app.py
# import streamlit as st
# import pickle
# import pandas as pd
# 
# st.set_page_config(page_title="Salary Prediction App", layout="centered")
# 
# # --- Load the pre-trained model ---
# try:
#     # Assuming the model is saved as 'linear_regression_model.pkl'
#     with open('linear_regression_model.pkl', 'rb') as file:
#         model = pickle.load(file)
#     st.success("Model loaded successfully!")
# except FileNotFoundError:
#     st.error("Error: 'linear_regression_model.pkl' not found. Please ensure the model file is in the correct directory.")
#     st.stop() # Stop the app if the model can't be loaded
# except Exception as e:
#     st.error(f"An error occurred while loading the model: {e}")
#     st.stop()
# 
# # --- Streamlit App Interface ---
# st.title("Salary Prediction with Linear Regression")
# st.write("Enter the years of experience to predict the corresponding salary.")
# 
# # Input widget for years of experience
# years_experience = st.slider(
#     "Years of Experience",
#     min_value=0.0,
#     max_value=20.0,
#     value=5.0,
#     step=0.5,
#     help="Drag the slider to select the years of experience"
# )
# 
# # Make prediction
# if st.button("Predict Salary"):
#     try:
#         # Create a DataFrame for the prediction input
#         input_df = pd.DataFrame({'YearsExperience': [years_experience]})
# 
#         # Predict salary
#         predicted_salary = model.predict(input_df)[0]
# 
#         st.subheader("Prediction")
#         st.success(f"Predicted Salary: ${predicted_salary:,.2f}")
#     except Exception as e:
#         st.error(f"An error occurred during prediction: {e}")
# 
# st.markdown("---")
# st.write("This app uses a simple linear regression model to predict salary.")
# 
# # Instructions to run the app
# st.sidebar.header("How to run this app?")
# st.sidebar.info("""1. Save this code as `app.py`.
# 2. Open your terminal or command prompt.
# 3. Navigate to the directory where you saved `app.py`.
# 4. Run the command: `streamlit run app.py`""")

"""Next, I'll run the Streamlit app in the background and use `localtunnel` to create a public URL."""

# Run the Streamlit app in the background on port 8501
!streamlit run app.py &>/dev/null &

# Expose the Streamlit app using localtunnel
!lt --port 8501

"""After executing the cell above, `localtunnel` will provide a public URL. Click on that URL to access your Streamlit app in your browser."""