# -*- coding: utf-8 -*-
"""ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWvGVELHEqDwaZRUUTYAF3MdJLrBlV2q
"""

import pandas as pd

df = pd.read_csv("Salary_Data.csv")
print(df.head())

print(df.isnull().sum())

df = df.dropna(subset=['Salary'])

from sklearn.preprocessing import LabelEncoder

df.columns = df.columns.str.strip()  # remove spaces

cols = ['Gender', 'Education Level', 'Job Title']

for col in cols:
    le = LabelEncoder()
    df[col] = df[col].astype(str)   # convert to string
    df[col] = le.fit_transform(df[col])

X = df.drop('Salary', axis=1)
y = df['Salary']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(x_train.shape, x_test.shape)

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

x_train = imputer.fit_transform(x_train)
x_test = imputer.transform(x_test)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", r2)

import joblib

joblib.dump(model, "linear_regression_model.pkl")

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

rf_model.fit(x_train, y_train)

y_pred_rf = rf_model.predict(x_test)

from sklearn.metrics import mean_squared_error, r2_score

mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest MSE:", mse_rf)
print("Random Forest R2:", r2_rf)

print("Linear Regression R2:", r2)
print("Random Forest R2:", r2_rf)

import joblib

joblib.dump(rf_model, "best_model.pkl")

